### ISSUE TITLE
Include Carbon Multiplier and Assumed Distance Travelled in Google Sheet output 

### ISSUE THREAD

**Issue by ghost** [TomGB/aaron-climate-counter#7]
Include Carbon Multiplier and Assumed Distance Travelled in Google Sheet output.

This is so that we don't need to track the changes we have made transforming the data into current output when potentially using it in the future.

**Comment by TomGB** [comment]
Completed in: https://github.com/TomGB/aaron-climate-counter/pull/10

Added the g / km for the selected transport type and added the multiplier (2x assuming the person is traveling to the conference and back)
